export type BusinessPersona = {
  id: string;
  name: string;
  persona: string;
  summary: string;
  template: string;
  templateName: string;
  catalogLabel: string;
  categoryLabel: string;
  highlight: string;
  sectionEyebrow: string;
  sectionTitle: string;
  carouselEyebrow: string;
  carouselTitle: string;
};

export const businessPersonas: BusinessPersona[] = [
  {
    id: 'general-store',
    name: 'General Store',
    persona: 'Standard',
    summary: 'Clean, modern storefront suitable for any business type – retail, products, or services.',
    template: 'luxe-market',
    templateName: 'Luxe Market',
    catalogLabel: 'product',
    categoryLabel: 'category',
    highlight: 'Premium shopping experience with direct WhatsApp checkout',
    sectionEyebrow: 'Featured items',
    sectionTitle: 'Browse our full catalog',
    carouselEyebrow: 'Trending now',
    carouselTitle: 'Our best selling products',
  },
  {
    id: 'retail-groceries',
    name: 'Retail & Groceries',
    persona: 'Mama Tunde',
    summary: 'Bulk foodstuffs, neighborhood retail, supermarkets, and everyday goods.',
    template: 'whatsapp-native',
    templateName: 'WhatsApp Native',
    catalogLabel: 'item',
    categoryLabel: 'aisle',
    highlight: 'Everyday essentials, easy WhatsApp ordering',
    sectionEyebrow: 'Shop essentials',
    sectionTitle: 'Fresh stock ready for pickup or delivery',
    carouselEyebrow: 'Popular today',
    carouselTitle: 'Fast-moving items customers ask for',
  },
  {
    id: 'fashion-apparel',
    name: 'Fashion & Apparel',
    persona: 'Chidi',
    summary: 'Boutiques, thrift sellers, bespoke apparel, shoes, bags, and accessories.',
    template: 'editorial',
    templateName: 'Editorial',
    catalogLabel: 'look',
    categoryLabel: 'collection',
    highlight: 'Premium looks with direct chat checkout',
    sectionEyebrow: 'New arrivals',
    sectionTitle: 'Curated pieces for your next look',
    carouselEyebrow: 'Featured fits',
    carouselTitle: 'Statement pieces from the catalog',
  },
  {
    id: 'food-vendor',
    name: 'Food Vendor',
    persona: 'Aisha',
    summary: 'Cloud kitchens, bakeries, lunch bowls, restaurants, and daily menus.',
    template: 'flash-sale',
    templateName: 'Flash Sale',
    catalogLabel: 'meal',
    categoryLabel: 'menu section',
    highlight: 'Lunch-rush ordering without scattered messages',
    sectionEyebrow: 'Menu',
    sectionTitle: 'Order fresh meals before the rush',
    carouselEyebrow: 'Chef picks',
    carouselTitle: 'Customer favorites ready to order',
  },
  {
    id: 'creator-digital',
    name: 'Creator & Digital Products',
    persona: 'Tobi',
    summary: 'E-books, courses, templates, music, PDFs, and instant downloads.',
    template: 'digital-studio',
    templateName: 'Digital Studio',
    catalogLabel: 'digital product',
    categoryLabel: 'library',
    highlight: 'Instant digital delivery after payment',
    sectionEyebrow: 'Digital library',
    sectionTitle: 'Downloadable products built for growth',
    carouselEyebrow: 'Best sellers',
    carouselTitle: 'Digital products people keep buying',
  },
  {
    id: 'faith-community',
    name: 'Faith Community',
    persona: 'Brother Samuel',
    summary: 'Church offerings, event registration, donations, books, and community programs.',
    template: 'whatsapp-native',
    templateName: 'WhatsApp Native',
    catalogLabel: 'offering',
    categoryLabel: 'ministry',
    highlight: 'Simple giving, events, and community payments',
    sectionEyebrow: 'Community desk',
    sectionTitle: 'Support, register, and give with ease',
    carouselEyebrow: 'Open now',
    carouselTitle: 'Current programs and giving options',
  },
  {
    id: 'school-education',
    name: 'School & Education',
    persona: 'Mrs. Okoro',
    summary: 'School fees, uniforms, books, events, lesson materials, and parent payments.',
    template: 'luxe-market',
    templateName: 'Luxe Market',
    catalogLabel: 'school item',
    categoryLabel: 'department',
    highlight: 'Organized payments for parents and pupils',
    sectionEyebrow: 'School payments',
    sectionTitle: 'Fees, uniforms, books, and school essentials',
    carouselEyebrow: 'Important',
    carouselTitle: 'Priority payments and school items',
  },
  {
    id: 'pharmacy-health',
    name: 'Pharmacy & Health',
    persona: 'Dr. Emeka',
    summary: 'Community pharmacies, wellness shops, prescription pre-orders, and consultations.',
    template: 'atelier',
    templateName: 'Atelier',
    catalogLabel: 'health item',
    categoryLabel: 'care category',
    highlight: 'Trusted pre-orders and health essentials',
    sectionEyebrow: 'Health catalog',
    sectionTitle: 'Wellness products and pharmacy essentials',
    carouselEyebrow: 'Recommended',
    carouselTitle: 'Frequently requested health items',
  },
  {
    id: 'beauty-service',
    name: 'Beauty & Services',
    persona: 'Sarah',
    summary: 'Stylists, makeup artists, salons, service bookings, deposits, and beauty products.',
    template: 'editorial',
    templateName: 'Editorial',
    catalogLabel: 'service',
    categoryLabel: 'service menu',
    highlight: 'Premium bookings, deposits, and beauty sales',
    sectionEyebrow: 'Services',
    sectionTitle: 'Book your next beauty experience',
    carouselEyebrow: 'Signature services',
    carouselTitle: 'Popular bookings and beauty picks',
  },
  {
    id: 'barber-shop',
    name: 'Barber Shop',
    persona: 'Ade the Barber',
    summary: 'Barbers and barbershops offering haircuts, shaves, lineups, and grooming services.',
    template: 'editorial',
    templateName: 'Editorial',
    catalogLabel: 'service',
    categoryLabel: 'service menu',
    highlight: 'Book your next cut, no calls needed',
    sectionEyebrow: 'Services',
    sectionTitle: 'Choose your style and book a slot',
    carouselEyebrow: 'Popular cuts',
    carouselTitle: 'Most booked barber services',
  },
  {
    id: 'home-services',
    name: 'Home Services',
    persona: 'Emeka the Fixer',
    summary: 'Painters, plumbers, electricians, tilers, carpenters, and other home repair professionals.',
    template: 'atelier',
    templateName: 'Atelier',
    catalogLabel: 'service',
    categoryLabel: 'service type',
    highlight: 'Book reliable home services with upfront pricing',
    sectionEyebrow: 'Services',
    sectionTitle: 'Quality home services, booked in minutes',
    carouselEyebrow: 'Top services',
    carouselTitle: 'Trusted services customers book',
  },
  {
    id: 'auto-repair',
    name: 'Auto Repair',
    persona: 'Chukwu Motors',
    summary: 'Mechanics, auto electricians, tyre shops, car detailing, and vehicle maintenance.',
    template: 'atelier',
    templateName: 'Atelier',
    catalogLabel: 'service',
    categoryLabel: 'service type',
    highlight: 'Transparent pricing, quick turnaround',
    sectionEyebrow: 'Services',
    sectionTitle: 'Auto repairs and maintenance, book now',
    carouselEyebrow: 'Common fixes',
    carouselTitle: 'Most requested auto services',
  },
  {
    id: 'cleaning-service',
    name: 'Cleaning Service',
    persona: 'Fresh Clean Co.',
    summary: 'Home cleaners, laundry services, fumigation, post-construction cleaning, and office cleaning.',
    template: 'whatsapp-native',
    templateName: 'WhatsApp Native',
    catalogLabel: 'service',
    categoryLabel: 'service type',
    highlight: 'Professional cleaning, easy online booking',
    sectionEyebrow: 'Services',
    sectionTitle: 'Schedule your cleaning today',
    carouselEyebrow: 'Popular packages',
    carouselTitle: 'Most booked cleaning services',
  },
  {
    id: 'event-services',
    name: 'Event Services',
    persona: 'Events by Kemi',
    summary: 'Event planners, photographers, caterers, MCs, decorators, and party vendors.',
    template: 'flash-sale',
    templateName: 'Flash Sale',
    catalogLabel: 'service',
    categoryLabel: 'event type',
    highlight: 'Memorable events, seamless booking',
    sectionEyebrow: 'Services',
    sectionTitle: 'Book for your next event',
    carouselEyebrow: 'Top picks',
    carouselTitle: 'Trending event services',
  },
  {
    id: 'tech-store',
    name: 'Tech & Repairs',
    persona: 'Ade Tech',
    summary: 'New and refurbished phones, audio gear, repair services, and device diagnostics.',
    template: 'atelier',
    templateName: 'Atelier',
    catalogLabel: 'gadget',
    categoryLabel: 'department',
    highlight: 'Quality gadgets and repairs, secure checkout',
    sectionEyebrow: 'Gadgets',
    sectionTitle: 'Browse our latest devices and services',
    carouselEyebrow: 'Hot deals',
    carouselTitle: 'Featured items and repairs',
  },
  {
    id: 'thrift-store',
    name: 'Thrift & Vintage',
    persona: 'Ada Finds',
    summary: 'Curated preloved wear, vintage denim, shoes, bags, and unique thrift pieces.',
    template: 'editorial',
    templateName: 'Editorial',
    catalogLabel: 'find',
    categoryLabel: 'collection',
    highlight: 'Unique handpicked thrift finds',
    sectionEyebrow: 'New drops',
    sectionTitle: 'Fresh thrift finds ready to ship',
    carouselEyebrow: 'Must haves',
    carouselTitle: 'Steals and unique pieces',
  },
  {
    id: 'laundry-service',
    name: 'Laundry & Dry Cleaning',
    persona: 'Laundry Pro',
    summary: 'Dry cleaning, washing, starching, alterations, and pickup/delivery options.',
    template: 'atelier',
    templateName: 'Atelier',
    catalogLabel: 'service',
    categoryLabel: 'laundry type',
    highlight: 'Professional laundry, starching & ironing services',
    sectionEyebrow: 'Services',
    sectionTitle: 'Schedule your laundry drop off or pick up',
    carouselEyebrow: 'Most popular',
    carouselTitle: 'Frequently requested laundry options',
  },
  {
    id: 'photographer-service',
    name: 'Photography & Video',
    persona: 'Visuals by Studio',
    summary: 'Photoshoots, event coverage, editing, portrait sessions, and equipment bookings.',
    template: 'editorial',
    templateName: 'Editorial',
    catalogLabel: 'package',
    categoryLabel: 'shoot type',
    highlight: 'Stunning captures, premium edits, and session slot booking',
    sectionEyebrow: 'Packages',
    sectionTitle: 'Browse our signature shoot packages',
    carouselEyebrow: 'Featured sessions',
    carouselTitle: 'Trending shoots and galleries',
  },
  {
    id: 'whatsapp-tv',
    name: 'WhatsApp TV & Advertising',
    persona: 'Promo Drop',
    summary: 'Status ad placements, broadcast slots, event promotions, and influencer shoutouts.',
    template: 'flash-sale',
    templateName: 'Flash Sale',
    catalogLabel: 'promo package',
    categoryLabel: 'ad slot',
    highlight: 'Direct status ad slot placements & viral shoutouts',
    sectionEyebrow: 'Ad Packages',
    sectionTitle: 'Book status views and event promotions',
    carouselEyebrow: 'Top packages',
    carouselTitle: 'Most booked advertising placements',
  },
  {
    id: 'estate-agent',
    name: 'Real Estate & Agency',
    persona: 'Property Hub',
    summary: 'Guided property viewings, property listings, consultations, valuations, and digital area reports.',
    template: 'luxe-market',
    templateName: 'Luxe Market',
    catalogLabel: 'property listing',
    categoryLabel: 'location',
    highlight: 'Guided viewings, property consults & valuations',
    sectionEyebrow: 'Properties',
    sectionTitle: 'Available viewings and property consulting',
    carouselEyebrow: 'Featured listings',
    carouselTitle: 'High demand properties and reports',
  },
];

