export interface City {
  slug: string;
  name: string;
  aliases?: string[];
}

export const NIGERIAN_CITIES: Record<string, City[]> = {
  'delta': [
    { slug: 'asaba', name: 'Asaba', aliases: ['asaba', 'okpanam'] },
    { slug: 'warri', name: 'Warri', aliases: ['warri', 'effurun', 'udu'] },
    { slug: 'abraka', name: 'Abraka', aliases: ['abraka', 'delsu'] },
    { slug: 'ughelli', name: 'Ughelli' },
    { slug: 'sapele', name: 'Sapele' },
    { slug: 'agbor', name: 'Agbor' },
    { slug: 'oghara', name: 'Oghara' },
    { slug: 'oleh', name: 'Oleh' },
    { slug: 'kwale', name: 'Kwale' },
    { slug: 'ozoro', name: 'Ozoro' },
    { slug: 'ogwashi-uku', name: 'Ogwashi-Uku' },
    { slug: 'ibusa', name: 'Ibusa' },
    { slug: 'effurun', name: 'Effurun' },
    { slug: 'agbarho', name: 'Agbarho' },
    { slug: 'koko', name: 'Koko' },
    { slug: 'obiaruku', name: 'Obiaruku' },
    { slug: 'issele-uku', name: 'Issele-Uku' },
    { slug: 'burutu', name: 'Burutu' },
    { slug: 'bomadi', name: 'Bomadi' },
    { slug: 'patani', name: 'Patani' },
    { slug: 'orerokpe', name: 'Orerokpe' },
  ],
  'edo': [
    { slug: 'benin-city', name: 'Benin City', aliases: ['benin city', 'benin', 'oba market'] },
    { slug: 'auchi', name: 'Auchi', aliases: ['auchi', 'fedpoly auchi'] },
    { slug: 'ekpoma', name: 'Ekpoma', aliases: ['ekpoma', 'aau'] },
    { slug: 'uromi', name: 'Uromi' },
    { slug: 'okada', name: 'Okada', aliases: ['okada', 'iuo'] },
    { slug: 'igarra', name: 'Igarra' },
    { slug: 'sabongida-ora', name: 'Sabongida-Ora' },
    { slug: 'agenegbode', name: 'Agenegbode' },
    { slug: 'igueben', name: 'Igueben' },
    { slug: 'fugar', name: 'Fugar' },
  ],
  'rivers': [
    { slug: 'port-harcourt', name: 'Port Harcourt', aliases: ['ph', 'port harcourt', 'peter odili'] },
    { slug: 'obio-akpor', name: 'Obio-Akpor', aliases: ['obio-akpor', 'rumuokoro', 'rumuodara'] },
    { slug: 'choba', name: 'Choba', aliases: ['choba', 'uniport'] },
    { slug: 'eleme', name: 'Eleme' },
    { slug: 'bonny', name: 'Bonny', aliases: ['bonny', 'bonny island'] },
    { slug: 'omoku', name: 'Omoku' },
    { slug: 'bori', name: 'Bori', aliases: ['bori', 'ken poly'] },
    { slug: 'ahoada', name: 'Ahoada' },
    { slug: 'degema', name: 'Degema' },
  ],
  'lagos': [
    { slug: 'ikeja', name: 'Ikeja', aliases: ['ikeja', 'computer village', 'allen avenue'] },
    { slug: 'lekki', name: 'Lekki', aliases: ['lekki', 'phase 1', 'jakande'] },
    { slug: 'victoria-island', name: 'Victoria Island', aliases: ['vi', 'victoria island', 'adeniyi jones'] },
    { slug: 'surulere', name: 'Surulere', aliases: ['surulere', 'adeniran ogunsanya', 'masha'] },
    { slug: 'yaba', name: 'Yaba', aliases: ['yaba', 'unilag', 'yabatech', 'akoka'] },
    { slug: 'ikorodu', name: 'Ikorodu', aliases: ['ikorodu', 'lasustech'] },
    { slug: 'ojo', name: 'Ojo', aliases: ['ojo', 'lasu', 'alaba'] },
    { slug: 'lagos-island', name: 'Lagos Island', aliases: ['lagos island', 'balogun', 'cms'] },
    { slug: 'epe', name: 'Epe' },
    { slug: 'badagry', name: 'Badagry' },
    { slug: 'gbagada', name: 'Gbagada', aliases: ['gbagada', 'anthony'] },
    { slug: 'festac', name: 'Festac', aliases: ['festac', 'mile 2'] },
    { slug: 'apapa', name: 'Apapa' },
    { slug: 'oshodi', name: 'Oshodi' },
  ],
  'fct-abuja': [
    { slug: 'wuse', name: 'Wuse', aliases: ['wuse', 'wuse ii', 'wuse 2'] },
    { slug: 'garki', name: 'Garki', aliases: ['garki', 'garki area 11', 'garki area 1'] },
    { slug: 'maitama', name: 'Maitama' },
    { slug: 'gwarinpa', name: 'Gwarinpa', aliases: ['gwarinpa', 'gwarinpa estate'] },
    { slug: 'asokoro', name: 'Asokoro' },
    { slug: 'jabi', name: 'Jabi', aliases: ['jabi', 'jabi lake mall'] },
    { slug: 'utako', name: 'Utako' },
    { slug: 'kubwa', name: 'Kubwa' },
    { slug: 'karu', name: 'Karu', aliases: ['karu', 'nyanya'] },
    { slug: 'lugbe', name: 'Lugbe' },
    { slug: 'gwagwalada', name: 'Gwagwalada', aliases: ['gwagwalada', 'uniabuja'] },
    { slug: 'kuje', name: 'Kuje' },
  ],
  'kaduna': [
    { slug: 'kaduna', name: 'Kaduna', aliases: ['kaduna', 'kasu', 'afit'] },
    { slug: 'zaria', name: 'Zaria', aliases: ['zaria', 'abu', 'kongo'] },
    { slug: 'kafanchan', name: 'Kafanchan' },
    { slug: 'samaru', name: 'Samaru', aliases: ['samaru', 'abu samaru'] },
  ],
  'kano': [
    { slug: 'kano', name: 'Kano', aliases: ['kano', 'buk', 'sabon gari kano', 'fagge', 'kofar ruwa', 'singa'] },
    { slug: 'wudil', name: 'Wudil', aliases: ['wudil', 'kust', 'adustech'] },
    { slug: 'bichi', name: 'Bichi' },
    { slug: 'gezawa', name: 'Gezawa' },
  ],
  'abia': [
    { slug: 'aba', name: 'Aba', aliases: ['aba', 'ariaria', 'ngwa'] },
    { slug: 'umuahia', name: 'Umuahia', aliases: ['umuahia', 'mouau'] },
    { slug: 'ohafia', name: 'Ohafia' },
  ],
  'anambra': [
    { slug: 'awka', name: 'Awka', aliases: ['awka', 'unizik'] },
    { slug: 'onitsha', name: 'Onitsha', aliases: ['onitsha', 'onitsha main market', 'head bridge'] },
    { slug: 'nnewi', name: 'Nnewi', aliases: ['nnewi', 'nkwo nnewi'] },
    { slug: 'ihiala', name: 'Ihiala', aliases: ['ihiala', 'coou uli', 'uli'] },
  ],
  'imo': [
    { slug: 'owerri', name: 'Owerri', aliases: ['owerri', 'futo', 'imsu', 'nekede'] },
    { slug: 'orlu', name: 'Orlu' },
    { slug: 'okigwe', name: 'Okigwe' },
  ],
  'enugu': [
    { slug: 'enugu', name: 'Enugu', aliases: ['enugu', 'unec', 'esut', 'coal camp'] },
    { slug: 'nsukka', name: 'Nsukka', aliases: ['nsukka', 'unn'] },
    { slug: 'ogurute', name: 'Ogurute' },
  ]
};
